### ISSUE TITLE
Output isn't printed to the console

### ISSUE THREAD

**Issue by jaydorsey** [jaydorsey/asdf-each#1]
Example command:

    asdf each ruby ruby -e "puts 'bar'"

I expected to see `bar` printed N times

Example real-ish world usage is that I sometimes like to compare my configurations between ruby versions to rule out strangeness related to build things that might have been missed/skipped:

    asdf each ruby ruby -e "puts RbConfig::CONFIG['MAINLIBS']"      

Instead of printing output, it prints a blank line and I'm not quite sure why.

**Comment by smridge** [comment]
To note, commands like `asdf each ruby ruby --version` do work as expected.

@lonelyelk I feel like you're good at solving these kinds of things 😄 Not sure if you have tried this plugin out yet?

**Comment by lonelyelk** [comment]
I will take a look during this weekend.

**Comment by lonelyelk** [comment]
Yes, it's definitely harder, when there are no tests. But basically these shell script manipulations remove quotes and treat everything as separate arguments:
```
ruby -e "puts 'a' my fancy 'program'" --===>> ruby -e puts 'a' my fancy 'program'
```

You can confirm it by running:
```
asdf each ruby ruby -e "puts 'a'; puts 'b'; puts 'c'" --===>> still only puts one line per version
asdf each ruby ruby -e "puts UNDEFINED end ) syntax error" --===>> still only one line per version (only puts)
```

Or you can create a shell file:
```sh
arrr=("$@")
shift
brrr="${arrr[*]}"

echo $arrr
echo $brrr
```

And run it:
```
$ ./test.sh arg1 arg2 "asd kfj '2p' ''''"
arg1
arg1 arg2 asd kfj '2p' ''''

$ ./test.sh arg1 arg2 'asd kfj "2p" ""'
arg1
arg1 arg2 asd kfj "2p" ""
```

For some reason trying to mess with quotes doesn't quite work either:

```
$ asdf each ruby ruby -e '"puts :c001 h4ck3r"'
-e:1: unterminated string meets end of file
"puts
... x times
```

Which means that unlike in my test script, asdf throws away everything after the first space or somehow manages to pass them as different arguments (which I doubt). So you need to apply space-less technic:

```
$ asdf each ruby ruby -e "puts(%Q(c0013r#{32.chr}h4ck3r))"
c0013r h4ck3r
c0013r h4ck3r
c0013r h4ck3r
c0013r h4ck3r
```

I don't know shell scripting well enough to suggest a fix of the top of my head, can look into it tomorrow. But I definitely can suggest to look into writing it in a more testable way and add tests :) Because it behaves somehow differently in the function.

**Comment by lonelyelk** [comment]
Ok, it behaves the same in the function and outside. You can reproduce it with:

```bash
arrr=("$@")
shift
brrr="${arrr[*]}"

echo $arrr
echo $brrr
ruby $brrr
```

Which behaves like this:

```
$ ./test.sh -e "puts 'a'"
-e
-e puts 'a'

^^^ empty line

$ ./test.sh -e "'puts :a'"
-e
-e 'puts :a'
-e:1: unterminated string meets end of file
'puts
```
